### ISSUE TITLE
Add repository filtering based on query string

### ISSUE THREAD

**Issue by afuetterer** [afuetterer/python-re3data#131]
# Tasks

- [x] add _build_query_params function
- [x] add query to list function
- [x] add query_params to _request function
- [x] add `--query` to cli
- [x] add tests
- [x] valid query that returns repositories, e.g. biosharing
- [x] invalid query that returns empty list, e.g. XXX
- [x] mypy passes

# What?

We want to be able to make calls like this:

```python
re3data.repositories.list(query="biosharing")
```

which is translated to

https://www.re3data.org/api/beta/repositories?query=biosharing

# How?

We need to build a query/params dict somewhere. Dict contains only non empty values. In this issue only query or nothing.

This affects the RepositoryManager and Client classes.
